// 金属数据
const MetallicMaterialsData = [
  {
    id: "0",
    materials: "金属材料",
    type: "铁/钢",
    handmade: "",
    tools: "切割/打磨",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "去支撑/喷砂",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "喷砂/热处理",
    iron: "",
    lathe: "",
    laser: "切割",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "切割/折弯",
  },
  {
    id: "1",
    materials: "",
    type: "铝/合金",
    handmade: "",
    tools: "切割/打磨",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "去支撑/喷砂",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "喷砂/阳极氧化",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "切割/折弯",
  },
  {
    id: "2",
    materials: "",
    type: "铜/合金",
    handmade: "",
    tools: "切割/打磨",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "去支撑/喷砂",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "喷砂/热处理",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "切割/折弯",
  },
  {
    id: "3",
    materials: "",
    type: "钨/合金",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "机加工",
    iron: "机加工",
    lathe: "机加工",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "4",
    materials: "",
    type: "钛/合金",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "去支撑/二次加工",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "机加工",
    iron: "机加工",
    lathe: "机加工",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "4",
    materials: "",
    type: "......",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
];

// 非金属数据
const NonMetallicMaterialsData = [
  {
    id: "5",
    materials: "非金属材料",
    type: "ABS",
    handmade: "",
    tools: "切割/打磨",
    fdm: "打磨/喷漆",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "清粉/染色",
    more: "",
    cnc: "机加工",
    iron: "机加工",
    lathe: "机加工",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "配色粉/固化",
    sheet_metal: "",
  },
  {
    id: "6",
    materials: "",
    type: "尼龙",
    handmade: "",
    tools: "切割/打磨",
    fdm: "去支撑",
    sla: "",
    mjf: "染色",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "机加工",
    iron: "机加工",
    lathe: "机加工",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "7",
    materials: "",
    type: "树脂",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "去支撑/固化/打磨/喷漆/电镀",
    mjf: "",
    polyjet: "去支撑",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "8",
    materials: "",
    type: "硅胶/TPU",
    handmade: "",
    tools: "真空灌胶",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "配色粉/固化",
    sheet_metal: "",
  },
  {
    id: "9",
    materials: "",
    type: "PEEK",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "10",
    materials: "",
    type: "PP",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "11",
    materials: "",
    type: "PC",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "12",
    materials: "",
    type: "PE",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "13",
    materials: "",
    type: "POM",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "机加工",
    iron: "机加工",
    lathe: "机加工",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "14",
    materials: "",
    type: "亚克力",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "切割/胶贴",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "15",
    materials: "",
    type: "玻纤",
    handmade: "打磨/涂胶/缠绕",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "清粉/染色",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "16",
    materials: "",
    type: "碳纤维",
    handmade: "打磨/涂胶/缠绕",
    tools: "",
    fdm: "去支撑",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "17",
    materials: "",
    type: "石英",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "机加工/抛光",
    iron: "机加工/抛光",
    lathe: "机加工/抛光",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
];

// 侧边菜单
const FabMenuItems = [
  {
    label: "NexMaker Fab 实验室",
    link: "https://www.nexmaker.com/",
    attrs: { key: "fab" },
  },
  { label: "Fab 实验室", link: "/lab/lab", attrs: { key: "fab" } },
  {
    label: "Fab Academy",
    link: "http://fabacademy.org/",
    attrs: { key: "fab" },
  },
  {
    label: "MIT Fab Lab 认证",
    link: "https://www.fablabs.io/",
    attrs: { key: "fab" },
  },
  { label: "AGV 教育方案", link: "agvedu/agv", attrs: { key: "fab" } },
];

const PrototypeMenuItems = [
  {
    label: "材料",
    link: "prototype/material",
    attrs: { key: "prototype" },
  },
  {
    label: "制造工艺",
    link: "/prototype/manufacture",
    items: [
      { label: "增材制造", link: "/prototype/add" },
      { label: "等材制造", link: "/prototype/equal" },
      { label: "减材制造", link: "/prototype/cnc" },
    ],
    attrs: { key: "prototype" },
  },
  {
    label: "后处理",
    link: "/prototype/postprocess",
    attrs: { key: "prototype" },
  },
  { label: "测试", link: "/prototype/test", attrs: { key: "prototype" } },
];

const SandtableMenuItems = [
  {
    label: "沙盘",
    link: "/sandtable/sandtable",
    attrs: { key: "sandtable" },
  },
  {
    label: "加工",
    link: "/sandtable/manufacure",
    attrs: { key: "sandtable" },
  },
  {
    label: "电控",
    link: "/sandtable/control",
    attrs: { key: "sandtable" },
  },
  {
    label: "数字化",
    link: "/sandtable/digital",
    attrs: { key: "sandtable" },
  },
  {
    label: "维护与升级",
    link: "/sandtable/maintain",
    attrs: { key: "sandtable" },
  },
];

// 顶部菜单
const MenuData = [
  {
    key: "fab",
    label: "Fab 课程方案",
    link: "/fab/fab",
    items: FabMenuItems,
  },
  {
    key: "prototype",
    label: "工程样机开发",
    link: "/prototype",
    items: PrototypeMenuItems,
  },
  {
    key: "explore",
    label: "探索",
    items: [
      {
        label: "NexMaker Fab 实验室",
        link: "/explore/readme",
      },
      { label: "沙盘", link: "/zh-cn/sandtable/sandtable" },
      { label: "AGV", link: "/zh-cn/agvedu/agvcase" },
      { label: "文章", link: "/zh-cn/explore/readme" },
    ],
  },
  {
    key: "prototype",
    label: "关于 ProFabX",
    link: "/readme",
  },
];

// 侧边栏侧栏（不完整）
const SideBarData = [
  {
    key: "fab",
    label: "Fab 课程方案",
    items: [...FabMenuItems],
  },
  { key: "prototype", label: "材料", items: [...PrototypeMenuItems] },
  { key: "sandtable", label: "沙盘", items: [...SandtableMenuItems] },

  // A group labelled “Start Here” containing two links.
  // {
  //   label: "Start Here",
  //   items: [
  //     { label: "Introduction", link: "/intro" },
  //     { label: "Next Steps", link: "/next-steps" },
  //   ],
  // },
  // A group linking to all pages in the reference directory.
];

export {
  MetallicMaterialsData,
  NonMetallicMaterialsData,
  MenuData,
  SideBarData,
};
