const MetallicMaterialsData = [
  {
    id: "0",
    materials: "金属材料",
    type: "铁/钢",
    handmade: "",
    tools: "切割/打磨",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "去支撑/喷砂",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "喷砂/热处理",
    iron: "",
    lathe: "",
    laser: "切割",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "切割/折弯",
  },
  {
    id: "1",
    materials: "",
    type: "铝/合金",
    handmade: "",
    tools: "切割/打磨",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "去支撑/喷砂",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "喷砂/阳极氧化",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "切割/折弯",
  },
  {
    id: "2",
    materials: "",
    type: "铜/合金",
    handmade: "",
    tools: "切割/打磨",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "去支撑/喷砂",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "喷砂/热处理",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "切割/折弯",
  },
  {
    id: "3",
    materials: "",
    type: "钨/合金",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "机加工",
    iron: "机加工",
    lathe: "机加工",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "4",
    materials: "",
    type: "钛/合金",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "去支撑/二次加工",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "机加工",
    iron: "机加工",
    lathe: "机加工",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "4",
    materials: "",
    type: "......",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
];

// 非金属数据
const NonMetallicMaterialsData = [
  {
    id: "5",
    materials: "非金属材料",
    type: "ABS",
    handmade: "",
    tools: "切割/打磨",
    fdm: "打磨/喷漆",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "清粉/染色",
    more: "",
    cnc: "机加工",
    iron: "机加工",
    lathe: "机加工",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "配色粉/固化",
    sheet_metal: "",
  },
  {
    id: "6",
    materials: "",
    type: "尼龙",
    handmade: "",
    tools: "切割/打磨",
    fdm: "去支撑",
    sla: "",
    mjf: "染色",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "机加工",
    iron: "机加工",
    lathe: "机加工",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "7",
    materials: "",
    type: "树脂",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "去支撑/固化/打磨/喷漆/电镀",
    mjf: "",
    polyjet: "去支撑",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "8",
    materials: "",
    type: "硅胶/TPU",
    handmade: "",
    tools: "真空灌胶",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "配色粉/固化",
    sheet_metal: "",
  },
  {
    id: "9",
    materials: "",
    type: "PEEK",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "10",
    materials: "",
    type: "PP",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "11",
    materials: "",
    type: "PC",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "12",
    materials: "",
    type: "PE",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "13",
    materials: "",
    type: "POM",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "机加工",
    iron: "机加工",
    lathe: "机加工",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "14",
    materials: "",
    type: "亚克力",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "切割/胶贴",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "15",
    materials: "",
    type: "玻纤",
    handmade: "打磨/涂胶/缠绕",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "清粉/染色",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "16",
    materials: "",
    type: "碳纤维",
    handmade: "打磨/涂胶/缠绕",
    tools: "",
    fdm: "去支撑",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "",
    iron: "",
    lathe: "",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
  {
    id: "17",
    materials: "",
    type: "石英",
    handmade: "",
    tools: "",
    fdm: "",
    sla: "",
    mjf: "",
    polyjet: "",
    slm: "",
    dlp_lcd: "",
    sls: "",
    more: "",
    cnc: "机加工/抛光",
    iron: "机加工/抛光",
    lathe: "机加工/抛光",
    laser: "",
    another_more: "",
    injection_molding: "",
    silicone_coating: "",
    sheet_metal: "",
  },
];

// 顶部菜单
const MenuData = [
  {
    key: "fab",
    label: "Fab 课程方案",
    link: "/zh-cn/fab/fab",
    items: [
      {
        label: "NexMaker Fab 实验室",
        link: "https://www.nexmaker.com/",
      },
      { label: "Fab 实验室", link: "/zh-cn/lab/lab" },
      { label: "Fab Academy", link: "http://fabacademy.org/" },
      { label: "MIT Fab Lab 认证", link: "https://www.fablabs.io/" },
      { label: "AGV 教育方案", link: "/zh-cn/agvedu/agv" },
    ],
  },
  {
    key: "prototype",
    label: "工程样机开发",
    link: "/zh-cn/prototype",
  },
  {
    key: "explore",
    label: "探索",
    items: [
      {
        label: "NexMaker Fab 实验室",
        link: "/zh-cn/explore/readme",
      },
      { label: "沙盘", link: "/zh-cn/sandtable/sandtable" },
      { label: "AGV", link: "/zh-cn/agvedu/agvcase" },
      { label: "文章", link: "/zh-cn/explore/readme" },
    ],
  },
  {
    key: "prototype",
    label: "关于 ProFabX",
    link: "/zh-cn/README",
  },
];

export { MetallicMaterialsData, NonMetallicMaterialsData, MenuData };
